version: "2"

services:
    factomd_node:
        container_name: factomd_node
        # build: factom/
        image: emyrk/factomd_testnet_community:v1
        depends_on:
            - nginx
        expose:
            - "8088"
            - "22"
            - "8108" 
            - "8109" 
            - "8110" 
            - "9876"
        ports:
            - "8110:8110"
            - "8108:22"
            - "8090:8090"
        volumes:
            - factomd_volume:/root/.factom/m2
            # - ./factom/factomd.conf:/root/.factom/m2/factomd.conf:ro
        # command: -sim_stdin=false -customnet=net -network=CUSTOM -startdelay=10
        networks:
            factomd:
                ipv4_address: 10.7.0.1


    elasticsearch:
        container_name: elasticsearch
        build:
            context: elasticsearch/
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        expose:
            - "9200"
            - "9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk

    logstash:
        container_name: logstash
        build:
            context: logstash/
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
            - "5000:5000"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk
            - factomd
        depends_on:
            - elasticsearch

    kibana:
        container_name: kibana
        build:
            context: kibana/
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5601:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch

    prometheus:
        container_name: prometheus
        build:
            context: prometheus/
        volumes:
            - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - factomd
        depends_on:
            - factomd_node

    grafana:
        container_name: grafana
        build:
            context: grafana/
        volumes:
            - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "3001:3000"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - factomd
        depends_on:
            - factomd_node

    nginx:
        container_name: nginx
        build:
            context: nginx/
        volumes:
            - ./nginx/html/:/usr/share/nginx/html/:ro
        expose:
            - "80"
        networks:
            - factomd

networks:
    factomd:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.7.0.0/16
                  gateway: 10.7.1.1
                  ip_range: 10.7.1.0/24
    elk:
        driver: bridge

volumes:
  factomd_volume: