version: "2"

services:
    factomd_node:
        container_name: factomd_node
        # build: factom/
        image: emyrk/factomd_testnet_community:latest
        depends_on:
            - nginx
        expose:
            - "22"
            - "8108" 
            - "8109" 
            - "8110" 
            - "9876"
            - "8088"
        ports:
            - "8110:8110"
            - "8220:22"
            - "8090:8090"
            - "8088:8088"
        volumes:
            - factomd_volume:/root/.factom/
        networks:
            factomd:
                ipv4_address: 10.7.0.1

    enterprise-wallet:
        container_name: enterprise-wallet
        build:
            context: enterprise-wallet/
        expose:
            - "8091"
        ports:
            - "8091:8091"
        volumes:
            - enterprise_volume:/root/.factom/
        networks:
            - factomd
        depends_on:
            - factomd_node

    prometheus:
        container_name: prometheus
        build:
            context: prometheus/
        volumes:
            - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_volume:/prometheus
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - factomd
        depends_on:
            - factomd_node

    grafana:
        container_name: grafana
        build:
            context: grafana/
        volumes:
            - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
            - grafana_volume:/var/lib/grafana
        ports:
            - "3001:3000"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - factomd
        depends_on:
            - factomd_node

    nginx:
        container_name: nginx
        build:
            context: nginx/
        volumes:
            - ./nginx/html/:/usr/share/nginx/html/:ro
        expose:
            - "80"
        networks:
            - factomd

networks:
    factomd:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.7.0.0/16
                  gateway: 10.7.1.1
                  ip_range: 10.7.1.0/24
    elk:
        driver: bridge

volumes:
  factomd_volume:
  grafana_volume:
  enterprise_volume:
  prometheus_volume: